#!/bin/bash
set -e
#
# This script is used by various other jobs in different repo to install ansible v1 and v2
#

echo "Running travis $0"

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

SETUP_VERSION="master"

# Be more verbose
SETUP_VERBOSITY=""

## Install Ansible 1.9.6
ANSIBLE_VERSIONS[0]="1.9.6"
INSTALL_TYPE[0]="pip"
ANSIBLE_V1_PATH="${ANSIBLE_VERSIONS[0]}"    # v1

## Install Ansible 2.0
ANSIBLE_VERSIONS[1]="2.0.20.0"
INSTALL_TYPE[1]="pip"
ANSIBLE_V2_PATH="${ANSIBLE_VERSIONS[1]}"  # v2

# Whats the default version
ANSIBLE_DEFAULT_VERSION="v2"

## Create a temp dir
filename=$( echo ${0} | sed  's|/||g' )
my_temp_dir="$(mktemp -dt ${filename}.XXXX)"
## Get setup
curl -s https://raw.githubusercontent.com/AutomationWithAnsible/ansible-setup/$SETUP_VERSION/setup.sh -o $my_temp_dir/setup.sh
## Run the setup
. $my_temp_dir/setup.sh
