---

driver                    :
    name                  : docker
    socket                : unix:///var/run/docker.sock
    use_sudo              : false
    run_options           : "-v <%= File.dirname(__FILE__) %>:/avm"

verifier                  :
  name                    : serverspec
  remote_exec             : false
  default_pattern         : true

provisioner               :
     name                 : shell

platforms:
 - name                   : "ubuntu1404"
   driver_config          :
     platform             : ubuntu
     image                : "ubuntu:14.04"

 - name                   : "ubuntu1604"
   driver_config          :
     platform             : ubuntu
     image                : "ubuntu:16.04"

 - name                   : "alpine34"
   driver_config          :
     image                : alpine:3.4
     platform             : alpine
     provision_command    :
              - apk add sudo
              - echo "auth       sufficient pam_rootok.so" > /etc/pam.d/su

suites:
    - name                : simple
      provisioner         :
        script            : <%= File.dirname(__FILE__) %>/test/integration/simple/run_as_kitchen.sh

    - name                : advanced
      provisioner         :
        script            : test/integration/advanced/run_as_kitchen.sh
