---
language: ruby
rvm:
  - 2.2
sudo: required
services:
  - docker

env:
  - KITCHEN_TEST="simple-ubuntu1404"
  - KITCHEN_TEST="simple-ubuntu1604"
  - KITCHEN_TEST="simple-alpine34"
  - KITCHEN_TEST="advanced-ubuntu1404"
  - KITCHEN_TEST="advanced-ubuntu1604"
  - KITCHEN_TEST="advanced-alpine34"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl git python-pip ruby ruby-dev build-essential autoconf
  - gem install bundler
  # Get ansible install
  - ruby --version
  - python --version
  - pip --version
  - bundler --version

install:
  - bundle install

script:
    - LC_ALL=C bundle exec kitchen test $KITCHEN_TEST

after_success:
    - echo "Success"