---

- hosts: all
  gather_facts: False
  connection: local
  tasks:
      - template:
          src="{{ ANSIBLE_VERSION_TEMPLATE_PATH }}"
          dest="{{ ANSIBLE_BASEDIR }}/avm"
          owner="{{ SETUP_USER }}"
          mode=0755
